# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blocc < Formula
  desc "Execute multiple commands and block Claude Code Hooks by returning exit 2 with stderr on failures 🛡️"
  homepage "https://github.com/shuntaka9576/blocc"
  version "0.5.0"

  on_macos do
    url "https://github.com/shuntaka9576/blocc/releases/download/v0.5.0/blocc_0.5.0_Darwin_amd64.tar.gz"
    sha256 "dd57c965c57bbd79fe965f20848e1b4eb5d613e40db28ac9edf1c6014dbbcf35"

    def install
      bin.install "blocc"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Blocc
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shuntaka9576/blocc/releases/download/v0.5.0/blocc_0.5.0_Linux_amd64.tar.gz"
      sha256 "343725f54c8a80f6778065a7b3a7d6bca43510b4a3f4b1fca5fd0705635eca95"
      def install
        bin.install "blocc"
      end
    end
  end

  test do
    system "#{bin}/blocc --help"
  end
end
