# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blocc < Formula
  desc "Execute multiple commands and block Claude Code Hooks by returning exit 2 with stderr on failures 🛡️"
  homepage "https://github.com/shuntaka9576/blocc"
  version "0.3.0"

  on_macos do
    url "https://github.com/shuntaka9576/blocc/releases/download/v0.3.0/blocc_0.3.0_Darwin_amd64.tar.gz"
    sha256 "e159a971c2bb5f9ccfb5f84c7ed71cb7942556e9ebfbc8279688c87793536154"

    def install
      bin.install "blocc"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Blocc
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shuntaka9576/blocc/releases/download/v0.3.0/blocc_0.3.0_Linux_amd64.tar.gz"
      sha256 "5438f086af713cb3d1a6b449981a20cb034b21794ed67e7ccf0b6fe401c56970"
      def install
        bin.install "blocc"
      end
    end
  end

  test do
    system "#{bin}/blocc --help"
  end
end
