# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cal2prompt < Formula
  desc "✨ Fetches your schedule (e.g., from Google Calendar) and converts it into a single LLM prompt. It can also run as an MCP (Model Context Protocol) server."
  homepage "https://shuntaka.dev/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/cal2prompt/releases/download/v0.1.1/cal2prompt_0.1.1_darwin_amd64.tar.gz"
      sha256 "e88b105046601ed88c63ba077193df139319aedbced7567ebe9a1febbfe90d37"

      def install
        bin.install "cal2prompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuntaka9576/cal2prompt/releases/download/v0.1.1/cal2prompt_0.1.1_darwin_arm64.tar.gz"
      sha256 "ea10b779c708403a7b3b39d5e7ba657b746fae01308e7c34ec44a3dae9627a26"

      def install
        bin.install "cal2prompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shuntaka9576/cal2prompt/releases/download/v0.1.1/cal2prompt_0.1.1_linux_amd64.tar.gz"
        sha256 "e223b5eca2899d0cf0b0cc3b0fc7873a0c78bae6fdb1e6344647c87a15c2dfe3"

        def install
          bin.install "cal2prompt"
        end
      end
    end
  end

  test do
    system "#{bin}/cal2prompt --help"
  end
end
