# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chathist < Formula
  desc "A lightweight CLI tool to view and export your AI coding agent's chat history."
  homepage "https://shuntaka.dev/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/chathist/releases/download/v0.2.0/chathist_0.2.0_darwin_amd64.tar.gz"
      sha256 "779a36fc297ea66052e2d61e277fd282742cc31a2ed2438c1217cfab5f7d34f6"

      def install
        bin.install "chathist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuntaka9576/chathist/releases/download/v0.2.0/chathist_0.2.0_darwin_arm64.tar.gz"
      sha256 "53570df0ebe073b84f5995aabf0b245e4150794b527d9536c733af75d93257aa"

      def install
        bin.install "chathist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuntaka9576/chathist/releases/download/v0.2.0/chathist_0.2.0_linux_amd64.tar.gz"
      sha256 "ade6bd6bd41d3f56ab568feede695af215fb1150235362a934889623b000bf5f"
      def install
        bin.install "chathist"
      end
    end
  end

  test do
    system "#{bin}/chathist --help"
  end
end
