# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddbrew < Formula
  desc "Simple DynamoDB utility"
  homepage "https://blog.hozi.dev/"
  version "0.0.5"

  on_macos do
    url "https://github.com/shuntaka9576/ddbrew/releases/download/v0.0.5/ddbrew_0.0.5_Darwin_amd64.tar.gz"
    sha256 "96d186882f74a29b43ce2f9796026f0640d6549a253365d9cbd48096f3eb456d"

    def install
      bin.install "ddbrew"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ddbrew
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/ddbrew/releases/download/v0.0.5/ddbrew_0.0.5_Linux_amd64.tar.gz"
      sha256 "f413a1888014bb501e3a8ef74f590f70b0b2b3d5a16ca7820683db58229ff804"

      def install
        bin.install "ddbrew"
      end
    end
  end

  test do
    system "#{bin}/ddbrew --help"
  end
end
