# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddbrew < Formula
  desc "Simple DynamoDB utility"
  homepage "https://blog.hozi.dev/"
  version "0.0.3"

  on_macos do
    url "https://github.com/shuntaka9576/ddbrew/releases/download/v0.0.3/ddbrew_0.0.3_Darwin_amd64.tar.gz"
    sha256 "5d57d2612f4795a3d83b611baeda3044f9cfda88a48a3bea1891fb42188894b3"

    def install
      bin.install "ddbrew"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ddbrew
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/ddbrew/releases/download/v0.0.3/ddbrew_0.0.3_Linux_amd64.tar.gz"
      sha256 "f1e5789dd4f4e83f3d240fa4a0cb8a75974a3087db886584f236b85266751c5e"

      def install
        bin.install "ddbrew"
      end
    end
  end

  test do
    system "#{bin}/ddbrew --help"
  end
end
