# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddbrew < Formula
  desc "Simple DynamoDB utility"
  homepage "https://blog.hozi.dev/"
  version "0.0.6"

  on_macos do
    url "https://github.com/shuntaka9576/ddbrew/releases/download/v0.0.6/ddbrew_0.0.6_Darwin_amd64.tar.gz"
    sha256 "cc1cbb2b7aa6c65da2ab08a2785235a378261172eb670ebf16e45205d345657f"

    def install
      bin.install "ddbrew"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ddbrew
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/ddbrew/releases/download/v0.0.6/ddbrew_0.0.6_Linux_amd64.tar.gz"
      sha256 "a591cccb31f576d052072f4a8514dac5c0f827fedf0dac4123c4929bf65ac685"

      def install
        bin.install "ddbrew"
      end
    end
  end

  test do
    system "#{bin}/ddbrew --help"
  end
end
