# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoFriPush < Formula
  desc "Don't Push to Production on Friday!"
  homepage "https://shuntaka.dev/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/no-fri-push/releases/download/v0.1.1/no-fri-push_0.1.1_darwin_amd64.tar.gz"
      sha256 "6c14756a582e093df9a0e64fc7e976a5d27c56bb4821ecc2a60f23b1209f001e"

      def install
        bin.install "no-fri-push"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuntaka9576/no-fri-push/releases/download/v0.1.1/no-fri-push_0.1.1_darwin_arm64.tar.gz"
      sha256 "3b8ffe78c567a199e2344b4c094d28fdf1a15e7df0016d3d1920d6f279819cd2"

      def install
        bin.install "no-fri-push"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shuntaka9576/no-fri-push/releases/download/v0.1.1/no-fri-push_0.1.1_linux_amd64.tar.gz"
        sha256 "581de3d1f9eb9b17b15a290223cea2004791688ec50b84d4704ae65384cd1376"

        def install
          bin.install "no-fri-push"
        end
      end
    end
  end

  test do
    system "#{bin}/no-fri-push --help"
  end
end
