# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoFriPush < Formula
  desc "Don't Push to Production on Friday!"
  homepage "https://shuntaka.dev/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/no-fri-push/releases/download/v0.1.0/no-fri-push_0.1.0_darwin_amd64.tar.gz"
      sha256 "ccf46d07b9fb56d3a9713483a718b21a37143647e3df43725aa6aac35fd809e2"

      def install
        bin.install "no-fri-push"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuntaka9576/no-fri-push/releases/download/v0.1.0/no-fri-push_0.1.0_darwin_arm64.tar.gz"
      sha256 "7fc58e3b2a4aa587a4a891b935391d6c355c2fc9c2c4c3838590b6ff394a3d14"

      def install
        bin.install "no-fri-push"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shuntaka9576/no-fri-push/releases/download/v0.1.0/no-fri-push_0.1.0_linux_amd64.tar.gz"
        sha256 "03d7913b1d4681c0106fd9a8fa5b9993afa7136499ad203a7baf308082014fff"

        def install
          bin.install "no-fri-push"
        end
      end
    end
  end

  test do
    system "#{bin}/no-fri-push --help"
  end
end
