# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oax < Formula
  desc "CLI for OpenAI's ChatGPT"
  homepage "https://blog.hozi.dev/"
  version "0.3.0"

  on_macos do
    url "https://github.com/shuntaka9576/oax/releases/download/v0.3.0/oax_0.3.0_Darwin_amd64.tar.gz"
    sha256 "e30d14ba969942033665a81ebce26fe054b1f3ad62492a91e86b02b3161a68c8"

    def install
      bin.install "oax"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Oax
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/oax/releases/download/v0.3.0/oax_0.3.0_Linux_amd64.tar.gz"
      sha256 "b69bff38040f219e94cf1369df31a817ee9b003157bb7f4e0dbc84bd86a9f72d"

      def install
        bin.install "oax"
      end
    end
  end

  test do
    system "#{bin}/oax --help"
  end
end
