# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oax < Formula
  desc "CLI for OpenAI's ChatGPT"
  homepage "https://blog.hozi.dev/"
  version "0.1.1"

  on_macos do
    url "https://github.com/shuntaka9576/oax/releases/download/v0.1.1/oax_0.1.1_Darwin_amd64.tar.gz"
    sha256 "c15a310a931c54723775e1bcfa56621f8e0470ffe570d5babbd6e3fe26a5a697"

    def install
      bin.install "oax"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Oax
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/oax/releases/download/v0.1.1/oax_0.1.1_Linux_amd64.tar.gz"
      sha256 "075d40e8243a6a0944839e3b044b989d88b7c877ee3b2cdb8ed29cef6ada3a2b"

      def install
        bin.install "oax"
      end
    end
  end

  test do
    system "#{bin}/oax --help"
  end
end
