# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacli < Formula
  desc "Slack CLI built with Rust"
  homepage "https://shuntaka.dev/"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shuntaka9576/slacli/releases/download/v0.0.1/slacli_0.0.1_darwin_arm64.tar.gz"
      sha256 "22038eabc79ba0c32c43d470e5092bfbac0c28a22ee7a4cf66516cf499e91830"

      define_method(:install) do
        bin.install "slacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shuntaka9576/slacli/releases/download/v0.0.1/slacli_0.0.1_linux_amd64.tar.gz"
      sha256 "3f504d23cf5773d4b4c983123e4c166b38177a62c39b0530f0aa1f95a69eecd8"
      define_method(:install) do
        bin.install "slacli"
      end
    end
  end

  test do
    system "#{bin}/slacli --help"
  end
end
