# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshcmd < Formula
  desc "Execute command to ssh host"
  homepage "https://blog.hozi.dev/"
  version "0.0.1"

  on_macos do
    url "https://github.com/shuntaka9576/sshcmd/releases/download/v0.0.1/sshcmd_0.0.1_Darwin_amd64.tar.gz"
    sha256 "ffa074c8f9afcd47fa8aadc16aba7e6620a925c13f64082b4d68aeb0d9dcac73"

    def install
      bin.install "sshcmd"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Sshcmd
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/sshcmd/releases/download/v0.0.1/sshcmd_0.0.1_Linux_amd64.tar.gz"
      sha256 "f9c4ff09469b1b6614aacbd0f9b338e69944865d4e2bf12d6e7f0d3c72442bc2"

      def install
        bin.install "sshcmd"
      end
    end
  end

  test do
    system "#{bin}/sshcmd --help"
  end
end
