# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshcmd < Formula
  desc "Execute command to ssh host"
  homepage "https://blog.hozi.dev/"
  version "0.0.1"

  on_macos do
    url "https://github.com/shuntaka9576/sshcmd/releases/download/v0.0.1/sshcmd_0.0.1_Darwin_amd64.tar.gz"
    sha256 "da8c69fdc3098487e6124ee9ccaf58c3c1adbd04141be711904d303e302dc685"

    def install
      bin.install "sshcmd"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Sshcmd
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/sshcmd/releases/download/v0.0.1/sshcmd_0.0.1_Linux_amd64.tar.gz"
      sha256 "c709d8704ccabfc61a37274904ea033eb327a4767ec7f2da7e459dccb9b0efda"

      def install
        bin.install "sshcmd"
      end
    end
  end

  test do
    system "#{bin}/sshcmd --help"
  end
end
