# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trr < Formula
  desc "🌿 Branch isolation tool using tmux + rsync. Create dedicated workspaces for each git branch with automatic tmux window management."
  homepage "https://shuntaka.dev/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shuntaka9576/trr/releases/download/v0.1.0/trr_0.1.0_darwin_amd64.tar.gz"
      sha256 "450d60afb955e30bbfa8cbeb833c6f82fd7e7551a92828c9834bc24b56d6352c"

      def install
        bin.install "trr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shuntaka9576/trr/releases/download/v0.1.0/trr_0.1.0_darwin_arm64.tar.gz"
      sha256 "9ebdc6d58d9cac9efdb3d62fb52889bd0fe848ad2cee6331bfb2145f1155ffb3"

      def install
        bin.install "trr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shuntaka9576/trr/releases/download/v0.1.0/trr_0.1.0_linux_amd64.tar.gz"
      sha256 "19434263915d077a4cce9277fb521ca0c07cdd2a7afb13b95bd47e75adb51cb8"
      def install
        bin.install "trr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shuntaka9576/trr/releases/download/v0.1.0/trr_0.1.0_linux_arm64.tar.gz"
      sha256 "c24b067da60cf791d905e2b115d91373dd3da87a05988ddca5210efbf5d48889"
      def install
        bin.install "trr"
      end
    end
  end

  test do
    system "#{bin}/trr --help"
  end
end
